//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HideSloth.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HideSloth.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Settings 的本地化字符串。
        /// </summary>
        internal static string ButtonAdvanced {
            get {
                return ResourceManager.GetString("ButtonAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Capacity 的本地化字符串。
        /// </summary>
        internal static string ButtonCheck {
            get {
                return ResourceManager.GetString("ButtonCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Here is the information about the capacity of the container and size of the selected file. 的本地化字符串。
        /// </summary>
        internal static string CapacityInfo {
            get {
                return ResourceManager.GetString("CapacityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capacity Info 的本地化字符串。
        /// </summary>
        internal static string CapainforLabel {
            get {
                return ResourceManager.GetString("CapainforLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Container(s) 的本地化字符串。
        /// </summary>
        internal static string ContainerLabel {
            get {
                return ResourceManager.GetString("ContainerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decode 的本地化字符串。
        /// </summary>
        internal static string DecodeRadio {
            get {
                return ResourceManager.GetString("DecodeRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encode 的本地化字符串。
        /// </summary>
        internal static string EncodeRadio {
            get {
                return ResourceManager.GetString("EncodeRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 En/Decode 的本地化字符串。
        /// </summary>
        internal static string EndeFrame {
            get {
                return ResourceManager.GetString("EndeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string FileLabel {
            get {
                return ResourceManager.GetString("FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;File(F) 的本地化字符串。
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string FilestringFrame {
            get {
                return ResourceManager.GetString("FilestringFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Help(H) 的本地化字符串。
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Idle {
            get {
                object obj = ResourceManager.GetObject("Idle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Input or Output String 的本地化字符串。
        /// </summary>
        internal static string InputLabel {
            get {
                return ResourceManager.GetString("InputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steganography and Encryption System 的本地化字符串。
        /// </summary>
        internal static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embed the same message/file to multipal files. Use ; among file names or select files. 的本地化字符串。
        /// </summary>
        internal static string MultpLabel {
            get {
                return ResourceManager.GetString("MultpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Options(O) 的本地化字符串。
        /// </summary>
        internal static string OptionMenu {
            get {
                return ResourceManager.GetString("OptionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Concole Log 的本地化字符串。
        /// </summary>
        internal static string OutputConsole {
            get {
                return ResourceManager.GetString("OutputConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Running {
            get {
                object obj = ResourceManager.GetObject("Running", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Secret File 的本地化字符串。
        /// </summary>
        internal static string SecretLabel {
            get {
                return ResourceManager.GetString("SecretLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String 的本地化字符串。
        /// </summary>
        internal static string StringLabel {
            get {
                return ResourceManager.GetString("StringLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Tools(T) 的本地化字符串。
        /// </summary>
        internal static string ToolMenu {
            get {
                return ResourceManager.GetString("ToolMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap wizard {
            get {
                object obj = ResourceManager.GetObject("wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap wizard2 {
            get {
                object obj = ResourceManager.GetObject("wizard2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
